name: offline_zen_stories
description: A Flutter package that provides calming Zen stories when offline.
version: 1.0.1
homepage: https://github.com/Suneel-DK/Offline-Zen-Stories

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0






    
